sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        albums:
            routes:
                list: app.albums.list
                detail: app.albums.detail
        price_packages:
            routes:
                list: app.price_packages.list
                detail: app.price_packages.detail