sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_search:
    type: portal
    resource: "@SuluSearchBundle/Resources/config/routing_website.yml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"

app_price_packages_index:
    path: /price-packages
    controller: App\Controller\Website\PricePackageController::index
    methods: [GET]

app_price_package_detail:
    path: /price-packages/{id}
    controller: App\Controller\Website\PricePackageController::detail
    methods: [GET]

when@dev:
    _portal_errors:
        resource: "@SuluWebsiteBundle/Resources/config/routing_error.yml"
        type: portal
