sulu_price_package.list:
    path: /price-packages
    controller: Sulu\Bundle\AdminBundle\Controller\AdminController::indexAction
    defaults:
        _routeScope:
            - admin

sulu_price_package.add_form:
    path: /price-packages/add
    controller: Sulu\Bundle\AdminBundle\Controller\AdminController::indexAction
    defaults:
        _routeScope:
            - admin

sulu_price_package.edit_form:
    path: /price-packages/:id
    controller: Sulu\Bundle\AdminBundle\Controller\AdminController::indexAction
    defaults:
        _routeScope:
            - admin 