app.get_price_packages:
    path: /price-packages
    controller: App\Controller\Admin\PricePackageController::cgetAction
    methods: GET

app.post_price_package:
    path: /price-packages
    controller: App\Controller\Admin\PricePackageController::postAction
    methods: POST

app.get_price_package:
    path: /price-packages/{id}
    controller: App\Controller\Admin\PricePackageController::getAction
    methods: GET

app.put_price_package:
    path: /price-packages/{id}
    controller: App\Controller\Admin\PricePackageController::putAction
    methods: PUT

app.delete_price_package:
    path: /price-packages/{id}
    controller: App\Controller\Admin\PricePackageController::deleteAction
    methods: DELETE 